name: Bug report
description: Report a reproducible problem in EXC Analyzer
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please provide enough detail to reproduce the issue reliably.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug clearly and briefly.
      placeholder: One-paragraph summary of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Include exact command(s), arguments, and order of steps.
      placeholder: |
        1) exc <command> ...
        2) ...
        3) ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Include full error text if available.
      placeholder: What happened instead?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11.9"
    validations:
      required: true

  - type: input
    id: exc_version
    attributes:
      label: EXC version
      description: Output of `exc --version`
      placeholder: "EXC Analyzer v1.x.x"
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Install method
      options:
        - pip
        - deb
        - source
        - other
    validations:
      required: true

  - type: dropdown
    id: lang_mode
    attributes:
      label: Language mode
      options:
        - en
        - tr
        - custom/other
    validations:
      required: false

  - type: checkboxes
    id: auth_context
    attributes:
      label: Security/Auth context (if relevant)
      options:
        - label: I was logged in with `exc login`
        - label: I saw keyring/credential-store errors
        - label: I am running in WSL/container/CI/SSH

  - type: textarea
    id: logs
    attributes:
      label: Sanitized logs/output
      description: Remove secrets/tokens before posting.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Screenshots, links, related issues, etc.
    validations:
      required: false
